
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.undo.UndoManager;
import javax.xml.bind.Marshaller;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu20925473g
 */
public class MainFrame extends javax.swing.JFrame {
    
    UndoManager undoManager = new UndoManager();
    
    public MainFrame() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnSave = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        miNew = new javax.swing.JMenuItem();
        miOpenFile = new javax.swing.JMenuItem();
        miSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        mnEdit = new javax.swing.JMenu();
        doUndo = new javax.swing.JMenuItem();
        doRedo = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setPreferredSize(new java.awt.Dimension(400, 400));

        jToolBar1.setRollover(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        btnSave.setText(bundle.getString("MainFrame.btnSave.text")); // NOI18N
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnOpen.setText(bundle.getString("MainFrame.btnOpen.text")); // NOI18N
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpen);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mnFile.setText(bundle.getString("MainFrame.mnFile.text")); // NOI18N

        miNew.setIcon(new ImageIcon(MainFrame.class.getResource("/com/sun/java/swing/plaf/windows/icons/File.gif")));
        miNew.setText(bundle.getString("MainFrame.miNew.text")); // NOI18N
        miNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewActionPerformed(evt);
            }
        });
        mnFile.add(miNew);

        miOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Folder-Open-icon.png"))); // NOI18N
        miOpenFile.setText(bundle.getString("MainFrame.miOpenFile.text")); // NOI18N
        miOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOpenFileActionPerformed(evt);
            }
        });
        mnFile.add(miOpenFile);

        miSave.setText(bundle.getString("MainFrame.miSave.text")); // NOI18N
        miSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaveActionPerformed(evt);
            }
        });
        mnFile.add(miSave);
        mnFile.add(jSeparator1);

        miExit.setText(bundle.getString("MainFrame.miExit.text")); // NOI18N
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mnFile.add(miExit);

        jMenuBar1.add(mnFile);

        mnEdit.setText(bundle.getString("MainFrame.mnEdit.text")); // NOI18N

        doUndo.setText(bundle.getString("MainFrame.doUndo.text")); // NOI18N
        doUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doUndoActionPerformed(evt);
            }
        });
        mnEdit.add(doUndo);

        doRedo.setText(bundle.getString("MainFrame.doRedo.text")); // NOI18N
        doRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doRedoActionPerformed(evt);
            }
        });
        mnEdit.add(doRedo);

        jMenuBar1.add(mnEdit);

        mnAbout.setText(bundle.getString("MainFrame.mnAbout.text")); // NOI18N
        jMenuBar1.add(mnAbout);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewActionPerformed
        // TODO add your handling code here:
         int n = JOptionPane.showConfirmDialog(this, "The file isn't saved, do you want to save it?", "", JOptionPane.YES_NO_CANCEL_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            saveFile();
        }
        if (n == JOptionPane.NO_OPTION) {
           textArea.setText("");
        }
        if (n == JOptionPane.CANCEL_OPTION) {
            
        }
        
    }//GEN-LAST:event_miNewActionPerformed
    private void saveFile() {
        JFileChooser saveFile = new JFileChooser();
        if (saveFile.showSaveDialog(saveFile) == JFileChooser.APPROVE_OPTION) {
            File savefile = saveFile.getSelectedFile();
            PrintWriter outputStream = null;
            if (savefile.exists()) {
                int n = JOptionPane.showConfirmDialog(this, "The file already exist, do you want to remove it?", " do you want to remove it?", JOptionPane.YES_NO_OPTION);
                if (n == JOptionPane.YES_OPTION) {
                    try {
                        outputStream = new PrintWriter(new FileWriter(savefile));
                        outputStream.print(textArea.getText());
                    } catch (IOException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    } finally {
                        
                        if (outputStream != null) {
                            outputStream.close();
                        }
                    }
                }
                
            }
            
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveFile();
    }//GEN-LAST:event_btnSaveActionPerformed
    private void addUndoRedo() {
        textArea.getDocument().addUndoableEditListener(undoManager);
        
    }

    private void openAndReadFile() {
        BufferedReader inputStream = null;
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        
        File f = chooser.getSelectedFile();
        // String filename = f.getAbsolutePath();

        // textArea.setText(filename);
        String textfile = "";
        try {
            inputStream = new BufferedReader(new FileReader(f));
            String line;
            
            while ((line = inputStream.readLine()) != null) {
                System.out.println(line);
                textfile += line + "\n";
            }
            
        } catch (IOException ex) {
            System.err.println("Error leyendo el fichero");
            
        } finally {
            if (inputStream != null) {
                
                try {
                    inputStream.close();
                    textArea.setText(textfile);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
                
            }
            
        }
        
    }
    private void miOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOpenFileActionPerformed
        // TODO add your handling code here:
        openAndReadFile();
        

    }//GEN-LAST:event_miOpenFileActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // TODO add your handling code here:
        openAndReadFile();
    }//GEN-LAST:event_btnOpenActionPerformed

    private void miSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaveActionPerformed
        // TODO add your handling code here:
        saveFile();
    }//GEN-LAST:event_miSaveActionPerformed

    private void doUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doUndoActionPerformed
        // TODO add your handling code here:
        undoManager.undo();
    }//GEN-LAST:event_doUndoActionPerformed

    private void doRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doRedoActionPerformed
        // TODO add your handling code here:
        undoManager.redo();
        
    }//GEN-LAST:event_doRedoActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        int n = JOptionPane.showConfirmDialog(this, "The file isn't saved, do you want to save it?", "", JOptionPane.YES_NO_CANCEL_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            saveFile();
        }
        if (n == JOptionPane.NO_OPTION) {
            System.exit(0);
        }
        if (n == JOptionPane.CANCEL_OPTION) {
            
        }
        
    }//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnSave;
    private javax.swing.JMenuItem doRedo;
    private javax.swing.JMenuItem doUndo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miNew;
    private javax.swing.JMenuItem miOpenFile;
    private javax.swing.JMenuItem miSave;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenu mnEdit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

    private void initMyComponents() {
        addUndoRedo();
    }
    
}
